AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - test/test_helper.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Metrics/AbcSize:
  Max: 17

Metrics/MethodLength:
  Max: 16